import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import ThemeSwitch from "@/components/ThemeSwitch";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { SidebarProvider } from "./contexts/menuContext";
import { Providers as ThemeProviders } from "./providers";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "htuien.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <ThemeProviders>
          <SidebarProvider>
            <Header />
            <Sidebar />
            <div className="mt-header-height xl:mt-0 xl:ml-sidebar-width-sm 2xl:ml-sidebar-width bg-light dark:bg-dark">
              {children}
              <ToastContainer />
            </div>
            <ThemeSwitch />
          </SidebarProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
