import Sidebar from "@/components/Sidebar";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ThemeSwitch from "@/components/ThemeSwitch";
import { Providers } from "./providers";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "htuien dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <Providers>
          <Sidebar />
          {children}
          <ThemeSwitch />
        </Providers>
      </body>
    </html>
  );
}
